/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PaginasBlancas;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.ListSelectionModel.SINGLE_SELECTION;

/**
 *
 * @author User
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblNombres = new javax.swing.JLabel();
        LblApellidos = new javax.swing.JLabel();
        LblDireccion = new javax.swing.JLabel();
        LblTelefono = new javax.swing.JLabel();
        TxtNombres = new javax.swing.JTextField();
        TxtApellidos = new javax.swing.JTextField();
        TxtDireccion = new javax.swing.JTextField();
        TxtTelefono = new javax.swing.JTextField();
        AgregarPersona = new javax.swing.JButton();
        ScrollNombres = new javax.swing.JScrollPane();
        ListNombres = new javax.swing.JList<>();
        EliminarPersona = new javax.swing.JButton();
        BorrarDirectorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblNombres.setText("Nombres");

        LblApellidos.setText("Apellidos");

        LblDireccion.setText("Direccion");

        LblTelefono.setText("Telefono");

        TxtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombresActionPerformed(evt);
            }
        });

        AgregarPersona.setText("Agregar persona");
        AgregarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPersonaActionPerformed(evt);
            }
        });

        ScrollNombres.setViewportView(ListNombres);

        EliminarPersona.setText("Eliminar persona");
        EliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPersonaActionPerformed(evt);
            }
        });

        BorrarDirectorio.setText("Borrar directorio");
        BorrarDirectorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarDirectorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarPersona)
                .addGap(132, 132, 132))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(TxtTelefono))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblDireccion)
                                .addGap(18, 18, 18)
                                .addComponent(TxtDireccion))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblApellidos)
                                .addGap(18, 18, 18)
                                .addComponent(TxtApellidos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblNombres)
                                .addGap(18, 18, 18)
                                .addComponent(TxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ScrollNombres)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(EliminarPersona)
                        .addGap(51, 51, 51)
                        .addComponent(BorrarDirectorio)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombres)
                    .addComponent(TxtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblApellidos)
                    .addComponent(TxtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDireccion)
                    .addComponent(TxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTelefono)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(AgregarPersona)
                .addGap(18, 18, 18)
                .addComponent(ScrollNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EliminarPersona)
                    .addComponent(BorrarDirectorio))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombresActionPerformed
                //ListNombres.setSelectionMode(SINGLE_SELECTION);
    DefaultListModel modelo = new DefaultListModel();
    DirectorioT DT = new DirectorioT();
    private void AgregarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPersonaActionPerformed
        // TODO add your handling code here:
        try{
            if(TxtNombres.getText().isBlank() || TxtApellidos.getText().isBlank() || TxtDireccion.getText().isBlank() || TxtTelefono.getText().isBlank()){
               JOptionPane.showMessageDialog(null, "Faltan campos por llenar");
            }
            else{
                Persona P = new Persona(TxtNombres.getText(), TxtApellidos.getText(), TxtDireccion.getText(), TxtTelefono.getText());
                DT.AgregarPersona(P);
                String Registro = P.Nombres + "-" + P.Apellidos + "-" + P.Direccion + "-" + P.Telefono;
                ListNombres.setSelectionMode(SINGLE_SELECTION);
                //DefaultListModel modelo = new DefaultListModel();
                modelo.addElement(Registro);
                ListNombres.setModel(modelo);
            
            }
//                Persona P = new Persona(TxtNombres.getText(), TxtApellidos.getText(), TxtDireccion.getText(), TxtTelefono.getText());
//                DT.AgregarPersona(P);
//                String Registro = P.Nombres + "-" + P.Apellidos + "-" + P.Direccion + "-" + P.Telefono;
//                ListNombres.setSelectionMode(SINGLE_SELECTION);
//                //DefaultListModel modelo = new DefaultListModel();
//                modelo.addElement(Registro);
//                ListNombres.setModel(modelo);

        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Caracteres no validos");
        }
        finally{
            TxtNombres.setText("");
            TxtApellidos.setText("");
            TxtDireccion.setText("");
            TxtTelefono.setText("");
        }
    }//GEN-LAST:event_AgregarPersonaActionPerformed

    private void BorrarDirectorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarDirectorioActionPerformed
        // TODO add your handling code here:
        modelo.clear();
        DT.BorrarDirectorio();
    }//GEN-LAST:event_BorrarDirectorioActionPerformed

    private void EliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPersonaActionPerformed
        // TODO add your handling code here:
        try{
            int i = ListNombres.getSelectedIndex();
            modelo.removeElementAt(i);
            DT.EliminarPersona(i);
            
        }
        catch(ArrayIndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(null, "No hay elementos para borrar");
        }
    }//GEN-LAST:event_EliminarPersonaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarPersona;
    private javax.swing.JButton BorrarDirectorio;
    private javax.swing.JButton EliminarPersona;
    private javax.swing.JLabel LblApellidos;
    private javax.swing.JLabel LblDireccion;
    private javax.swing.JLabel LblNombres;
    private javax.swing.JLabel LblTelefono;
    private javax.swing.JList<String> ListNombres;
    private javax.swing.JScrollPane ScrollNombres;
    private javax.swing.JTextField TxtApellidos;
    private javax.swing.JTextField TxtDireccion;
    private javax.swing.JTextField TxtNombres;
    private javax.swing.JTextField TxtTelefono;
    // End of variables declaration//GEN-END:variables
}
